"""
Email Service
Sends AI-generated summaries to recipients via the Resend API.
Formats the summary into a professional HTML email template.
"""

import os
import resend
from fastapi import HTTPException


def _get_html_template(summary: str, filename: str) -> str:
    """Generate a professional HTML email template."""
    # Convert markdown-like formatting to HTML
    paragraphs = summary.split("\n\n")
    html_body = ""
    for para in paragraphs:
        para = para.strip()
        if not para:
            continue
        # Handle headers (lines starting with ## or #)
        if para.startswith("## "):
            html_body += f'<h3 style="color:#1a1a2e;margin-top:24px;margin-bottom:8px;font-size:16px;">{para[3:]}</h3>'
        elif para.startswith("# "):
            html_body += f'<h2 style="color:#1a1a2e;margin-top:24px;margin-bottom:12px;font-size:20px;">{para[2:]}</h2>'
        elif para.startswith("**") and para.endswith("**"):
            html_body += f'<h3 style="color:#1a1a2e;margin-top:24px;margin-bottom:8px;font-size:16px;font-weight:600;">{para[2:-2]}</h3>'
        else:
            # Replace bold markers
            formatted = para.replace("**", "<strong>", 1)
            while "**" in formatted:
                formatted = formatted.replace("**", "</strong>", 1)
                if "**" in formatted:
                    formatted = formatted.replace("**", "<strong>", 1)
            # Handle bullet points
            if para.startswith("- ") or para.startswith("• "):
                items = [line.lstrip("- •").strip() for line in para.split("\n") if line.strip()]
                html_body += '<ul style="margin:8px 0;padding-left:20px;">'
                for item in items:
                    html_body += f'<li style="margin:4px 0;color:#333;line-height:1.6;">{item}</li>'
                html_body += "</ul>"
            else:
                html_body += f'<p style="color:#333;line-height:1.8;margin:12px 0;font-size:15px;">{formatted}</p>'

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f0f2f5;font-family:'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:32px 16px;">
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#1a1a2e 0%,#16213e 50%,#0f3460 100%);border-radius:16px 16px 0 0;padding:40px 32px;text-align:center;">
      <h1 style="color:#fff;margin:0 0 8px;font-size:24px;font-weight:700;letter-spacing:-0.5px;">
        📊 Sales Insight Brief
      </h1>
      <p style="color:#a8b2d1;margin:0;font-size:14px;">
        Auto-generated from <strong style="color:#64ffda;">{filename}</strong>
      </p>
    </div>
    <!-- Body -->
    <div style="background:#fff;padding:32px;border-radius:0 0 16px 16px;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
      {html_body}
      <!-- Footer -->
      <div style="margin-top:32px;padding-top:20px;border-top:1px solid #e8e8e8;text-align:center;">
        <p style="color:#888;font-size:12px;margin:0;">
          Generated by <strong>Sales Insight Automator</strong> · Powered by Rabbitt AI
        </p>
      </div>
    </div>
  </div>
</body>
</html>"""


async def send_summary_email(
    recipient: str, summary: str, filename: str
) -> dict:
    """Send the AI-generated summary to the recipient's email."""
    api_key = os.getenv("RESEND_API_KEY", "")
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="Email service is not configured. Please set the RESEND_API_KEY.",
        )

    sender = os.getenv("SENDER_EMAIL", "onboarding@resend.dev")
    html_content = _get_html_template(summary, filename)

    try:
        resend.api_key = api_key

        params = {
            "from": f"Sales Insight Automator <{sender}>",
            "to": [recipient],
            "subject": f"📊 Sales Insight Brief — {filename}",
            "html": html_content,
        }

        email_response = resend.Emails.send(params)
        return {"status": "sent", "email_id": email_response.get("id", "unknown")}

    except Exception as e:
        raise HTTPException(
            status_code=502,
            detail=f"Failed to send email: {str(e)}",
        )
